//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BirthMonth
    {
        public BirthMonth()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int BirthMonthID { get; set; }

        [Display(Name="Birth Month")]
        public string BirthMonthName { get; set; }

        [Display(Name ="Birth Month")]
        public int BirthMonthNum { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
