//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustomerID { get; set; }

        [Display(Name="First Name")]
        [StringLength(50, ErrorMessage = "This field cannot exceed 50 characters.")]
        public string FirstName { get; set; }

        [Display(Name ="Last Name")]
        [StringLength(50, ErrorMessage = "This field cannot exceed 50 characters.")]
        public string LastName { get; set; }
   
        [Range(0, 120, ErrorMessage = "Value for {0} must be between {1} and {2}")]
        public int Age { get; set; }

        public int BirthMonthID { get; set; }
        public int FavoriteColorID { get; set; }

        [Display(Name ="Number of Siblings")]
        [Range(-100, 100, ErrorMessage = "Value for {0} must be between {1} and {2}")]
        public int NumberOfSiblings { get; set; }
    
        public virtual BirthMonth BirthMonth { get; set; }
        public virtual FavoriteColor FavoriteColor { get; set; }
    }
}
